image: "${GLOBAL_IMAGE_NAME}:${GLOBAL_IMAGE_TAG}"

# https://gitlab.com/patoperpetua/pipelines-npm/tree/master/src
include:
  - project: 'singletonsd/pipelines/npm'
    file: '/src/.gitlab-ci-main.yml'

variables:
  GLOBAL_IMAGE_NAME: "node"
  GLOBAL_IMAGE_TAG: "8-alpine"
  TEST_STATIC_ALL: "true"
  ORIGINAL_REPOSITORY: "ravimosharksas/apis/task/app-nodejs"
  NODE_COMMON_INSTALL_BEFORE: "python make gcc g++"
  NODE_COMMON_DOCKER_PACKAGE: "true"

stages:
  - install
  - test_static
  - build
  - test_dynamic
  - package
